version: '3.1'

services:

  wordpress:
    image: goteo/wordpress-plugin:0.2
    restart: always
    ports:
      - 3000:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpressuser
      WORDPRESS_DB_PASSWORD: wordpresspass
      WORDPRESS_DB_NAME: wordpressdb

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: wordpressdb
      MYSQL_USER: wordpressuser
      MYSQL_PASSWORD: wordpresspass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    ports: 
      - 33060:3306
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
